export const ROUTES = {
  LOGIN: '/login',
  HOME: '/home',
  SEARCH: '/search',
  CATEGORY: '/category',
  PRODUCT_DETAIL: '/product/:id',
  PUBLISH: '/publish',
  PUBLISH_EDIT: '/publish/edit/:id',
  CHAT_LIST: '/chat',
  CHAT_DIALOG: '/chat/:uid',
  ME: '/me',
  ME_PROFILE: '/me/profile',
  ME_PRODUCTS: '/me/products',
  ME_FAVORITES: '/me/favorites',
  ME_HISTORY: '/me/history',
  ME_ORDERS: '/me/orders',
  ME_SETTINGS: '/me/settings',
  NOTIFICATIONS: '/notifications',
} as const;
