export default {
  pages: [
    'pages/login/index',
    'pages/home/index',
    'pages/category/index',
    'pages/search/index',
    'pages/product-detail/index',
    'pages/publish/index',
    'pages/publish-edit/index',
    'pages/chat/index',
    'pages/chat-detail/index',
    'pages/me/index',
    'pages/me-profile/index',
    'pages/me-products/index',
    'pages/me-favorites/index',
    'pages/me-history/index',
    'pages/me-orders/index',
    'pages/me-settings/index',
    'pages/notifications/index',
    'pages/cart/index',
    'pages/wallet/index',
    'pages/bargains/index',
    'pages/report/index',
    'pages/address/index',
  ],
  window: {
    backgroundTextStyle: 'dark',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: '校园二手交易',
    navigationBarTextStyle: 'black',
    backgroundColor: '#F5F7FA',
  },
  tabBar: {
    custom: false,
    color: '#8A8A8A',
    selectedColor: '#2B8CFF',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      { pagePath: 'pages/home/index', text: '首页', iconPath: 'assets/icons/tab-home.png', selectedIconPath: 'assets/icons/tab-home-active.png' },
      { pagePath: 'pages/cart/index', text: '购物车', iconPath: 'assets/icons/tab-cart.png', selectedIconPath: 'assets/icons/tab-cart-active.png' },
      { pagePath: 'pages/publish/index', text: '发布', iconPath: 'assets/icons/tab-publish.png', selectedIconPath: 'assets/icons/tab-publish-active.png' },
      { pagePath: 'pages/chat/index', text: '消息', iconPath: 'assets/icons/tab-chat.png', selectedIconPath: 'assets/icons/tab-chat-active.png' },
      { pagePath: 'pages/me/index', text: '我的', iconPath: 'assets/icons/tab-me.png', selectedIconPath: 'assets/icons/tab-me-active.png' },
    ],
  },
};
